--display how many employees manage by each manager?

SELECT * FROM EMPLOYEES
ORDER BY MANAGER_ID;

SELECT MANAGER_ID,COUNT(*)
FROM EMPLOYEES
GROUP BY MANAGER_ID;

--HOW MANY EMPLOYEES ARE IT PROGAMMER	

SELECT COUNT(*) FROM EMPLOYEES
WHERE JOB_ID='IT_PROG';

SELECT JOB_ID,COUNT(*)
FROM EMPLOYEES
GROUP BY JOB_ID;

SELECT JOB_ID,COUNT(*)
FROM EMPLOYEES
WHERE JOB_ID='IT_PROG'
GROUP BY JOB_ID;


--DISPLAY SUM OF SALARY OF EACH DEPARTMENT

SELECT DEPARTMENT_ID,SALARY FROM EMPLOYEES
ORDER BY DEPARTMENT_ID;


SELECT DEPARTMENT_ID,SUM(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
ORDER BY DEPARTMENT_ID;

SELECT FIRST_NAME,LAST_NAME
FROM EMPLOYEES
ORDER BY FIRST_NAME;


SELECT * FROM EMPLOYEES;

SELECT JOB_ID,DEPARTMENT_ID,COUNT(*)
FROM EMPLOYEES
GROUP BY JOB_ID,DEPARTMENT_ID
ORDER BY DEPARTMENT_ID;


SELECT DEPARTMENT_ID,SUM(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
ORDER BY DEPARTMENT_ID;

SELECT DEPARTMENT_ID,SALARY,COUNT(*)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID,SALARY
ORDER BY DEPARTMENT_ID;

--DISPLAY AVERAGE SALARY OF EACH DEPARTMENT

SELECT DEPARTMENT_ID,AVG(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

--DISPLAY HOW MANY EMPLOYEES JOINED EACH YEAR.

SELECT HIRE_DATE,COUNT(*)
FROM EMPLOYEES
GROUP BY HIRE_DATE;

SELECT TO_CHAR(HIRE_DATE,'YYYY'),COUNT(*)
FROM EMPLOYEES
GROUP BY TO_CHAR(HIRE_DATE,'YYYY');

--display the year in which more than 10 employees join

SELECT TO_CHAR(HIRE_DATE,'YYYY'),COUNT(*)
FROM EMPLOYEES
GROUP BY TO_CHAR(HIRE_DATE,'YYYY')
HAVING COUNT(*)>10;

--display duplicate of first name 

SELECT FIRST_NAME,COUNT(*)
FROM EMPLOYEES
GROUP BY FIRST_NAME
HAVING COUNT(*)>1;

--display the count of employees in each department whose average salary is greater than 10000?

SELECT DEPARTMENT_ID,COUNT(*)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

SELECT DEPARTMENT_ID,COUNT(*)
FROM EMPLOYEES
WHERE SALARY>10000
GROUP BY DEPARTMENT_ID;

SELECT DEPARTMENT_ID,COUNT(*)
FROM EMPLOYEES
--WHERE SALARY>10000
GROUP BY DEPARTMENT_ID
HAVING AVG(SALARY)>10000;;

--display how many emp joined in each month of each year 2003 ?

SELECT TO_CHAR(HIRE_DATE,'MON'),COUNT(*)
FROM EMPLOYEES
GROUP BY TO_CHAR(HIRE_DATE,'MON');

SELECT TO_CHAR(HIRE_DATE,'MON'),COUNT(*)
FROM EMPLOYEES
WHERE TO_CHAR(HIRE_DATE,'YYYY')='2003'
GROUP BY TO_CHAR(HIRE_DATE,'MON')
ORDER BY TO_CHAR(HIRE_DATE,'MM');

SELECT TO_CHAR(HIRE_DATE,'MON')
FROM EMPLOYEES
ORDER BY TO_CHAR(HIRE_DATE,'MON');

SELECT TO_CHAR(HIRE_DATE,'MM')
FROM EMPLOYEES
ORDER BY TO_CHAR(HIRE_DATE,'MM');
